version: "3"
services:
  redhat:
    build: .
    privileged: true
    tty: true
    stdin_open: true
    user: root
    networks:
      - inno_net
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
  
#   mysql:
#     image: mysql:latest
#     container_name: mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: mytest
#       MYSQL_USER: testuser
#       MYSQL_PASSWORD: testpassword
#     networks:
#       - inno_net

networks:
  inno_net:
    driver: bridge
    
